version: '3.7'
services:
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - 8000:80
      volumes:
        - ./src:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mysql
      networks:
        - laravel

    mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      environment:
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT: admin.root
        MYSQL_ROOT_PASSWORD: admin.root
      ports:
        - 33069:3306
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        - laravel

    php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: php
      volumes:
        - ./src:/var/www/html
      ports:
        - 9000:80
      networks:
        - laravel

networks:
  laravel: